# Set prefix to Ctrl Space
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# General settings
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'  # true color support
set -g base-index 1              # windows start at 1, more natural
set -g detach-on-destroy off     # don't exit tmux when closing a session
set -g escape-time 0             # important for nvim, removes delay
set -g history-limit 1000000     # more scrollback
set -g renumber-windows on       # keeps window numbers tidy
set -g set-clipboard on          # system clipboard
set -g status-position top       # matter of taste
setw -g mode-keys vi             # vi keys in copy mode

# Plugin environment location
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Catppuccin config
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "directory"
set -g @catppuccin_status_modules_left "session"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
